import { createIcons, Plane, ChevronDown, Pause, Play, RotateCcw, Sun, Plus, Minus, Scan, Tags, Navigation2, X, Check, Download, ArrowRight, CornerDownLeft, PlaneLanding, Undo2, ArrowUpRight, PlaneTakeoff, Route } from 'lucide';
import airportData from '../dist/data/egph.json';
import { GroundSim, statusNames } from './sim.js';
import { AirportMap } from './map.js';
const $=id=>document.getElementById(id);
const icon=name=>`<i data-lucide="${name}"></i>`;
const icons={Plane,ChevronDown,Pause,Play,RotateCcw,Sun,Plus,Minus,Scan,Tags,Navigation2,X,Check,Download,ArrowRight,CornerDownLeft,PlaneLanding,Undo2,ArrowUpRight,PlaneTakeoff,Route};
const refreshIcons=()=>createIcons({icons,attrs:{'stroke-width':1.7}});
const formatTime=t=>new Date((8*3600+Math.floor(t))*1000).toISOString().slice(11,19);
let sim,map,selected=1,speed=4,paused=false,filter='all',waypoints=[],destination='',toastTimer,lastDetail='',lastStrips='',lastLogs='';
let planning=false,modalPaused=null;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4000);}
function select(id){selected=id;waypoints=[];planning=false;destination='';lastDetail='';if(map){map.selected=id;map.preview=[];map.waypoints=[];}render();}
function pause(value){paused=value;$('pause').innerHTML=icon(paused?'play':'pause');$('pause').title=paused?'Resume simulation':'Pause simulation';$('pause').setAttribute('aria-label',$('pause').title);$('shift-label').textContent=paused?'PAUSED':'DAY SHIFT';refreshIcons();}
function showDialog(id){modalPaused=paused;pause(true);$(id).showModal();}
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('close',()=>{if(modalPaused!==null){pause(modalPaused);modalPaused=null;}});
function available(p){return ['ready','inbound'].includes(p.state)||(['taxi','taxiin'].includes(p.state)&&p.held);}
function preview(){const p=sim.planes.find(p=>p.id===selected);if(!p||!available(p))return;planning=true;if(p.direction==='arrival'&&!destination)destination=sim.freeStands()[0]?.id||'';
  const target=p.direction==='arrival'?sim.stands.get(destination)?.node:sim.data.departureHold;map.preview=target?sim.plan(p,target,waypoints):[];map.waypoints=waypoints;
  if(!map.preview.length)toast('No taxi route is available to this destination.');lastDetail='';render();
}
function issue(action){const result=sim.command(selected,action,{stand:destination,waypoints});if(!result.ok){toast(result.message);return;}planning=false;waypoints=[];map.preview=[];map.waypoints=[];lastDetail='';render();}
function flightDetail(p){if(!p)return '<div class="empty">Select a flight strip.</div>';
  const arrival=p.direction==='arrival';const state=p.blocked?'Traffic ahead / holding':p.held?'Holding position':statusNames[p.state];let controls='';
  if(p.state==='gate')controls=`<button class="primary" data-action="pushback">${icon('corner-down-left')} Approve pushback</button>`;
  else if(p.state==='approach')controls=`<div class="actions"><button class="primary" data-action="land" ${sim.runwayOwner?'disabled':''}>${icon('plane-landing')} Clear to land · 24</button><button class="secondary" data-action="goaround">${icon('undo-2')} Go around</button></div>`;
  else if(p.state==='holding')controls=`<button class="primary" data-action="lineup" ${sim.runwayOwner?'disabled':''}>${icon('arrow-up-right')} Line up & wait · 24</button>`;
  else if(p.state==='linedup')controls=`<button class="primary" data-action="takeoff">${icon('plane-takeoff')} Cleared for takeoff</button>`;
  else if(available(p)){
    const opts=sim.data.stands.map(s=>{const occupied=sim.planes.some(q=>q.id!==p.id&&q.stand===s.id&&q.state!=='done');return `<option value="${s.id}" ${s.id===destination?'selected':''} ${occupied?'disabled':''}>Stand ${s.id}${occupied?' · occupied':''}</option>`;}).join('');
    controls=`${arrival?`<label class="clearance-title" for="stand-select">DESTINATION STAND</label><select id="stand-select" class="destination-select"><option value="">Assign stand</option>${opts}</select>`:''}<div class="actions"><button class="${planning?'secondary':'primary'}" id="preview-route">${icon('route')} ${planning?'Update route':'Plan taxi route'}</button>${planning?`<div class="clearance-title">${waypoints.length?'VIA '+waypoints.length+' WAYPOINTS':'PROPOSED CLEARANCE'} <button id="clear-waypoints">Reset</button></div><div class="route-summary">${sim.routeNames(map.preview).join(' → ')||'Apron'} → ${arrival?'Stand '+destination:'D1 / RWY 24'}</div><button class="primary" data-action="taxi" ${map.preview.length<2?'disabled':''}>${icon('check')} Issue taxi clearance</button>`:''}${p.held?`<button class="secondary" data-action="hold">${icon('play')} Resume current route</button>`:''}</div>`;
  }else if(['pushback','taxi','taxiin'].includes(p.state))controls=`<button class="secondary" data-action="hold">${icon(p.held?'play':'pause')} ${p.held?'Continue':'Hold position'}</button>`;
  else controls=`<div class="route-summary">${p.state==='parked'?'Turnaround in progress':p.state==='done'?'Handed over to departure':p.state==='landing'?'Landing clearance active':'Runway clearance active'}</div>`;
  return `<span class="eyebrow">${arrival?'ARRIVAL':'DEPARTURE'} / FLIGHT ${String(p.id).padStart(2,'0')}</span><div class="flight-title"><h2>${p.call}</h2><span class="plane-type">${p.type}</span></div><div class="flight-state">${state}</div><dl class="flight-facts"><div><dt>${p.stand?'STAND':'POSITION'}</dt><dd>${p.stand||(['holding','lineup','linedup','takeoff'].includes(p.state)?'D1 / Runway 24':p.state==='approach'?'Final approach':'Taxiway')}</dd></div><div><dt>${p.state==='approach'?'CLEARANCE WINDOW':'DESTINATION'}</dt><dd>${p.state==='approach'?Math.max(0,Math.ceil(210-p.wait))+' sec':arrival?(p.stand?'Stand '+p.stand:'Awaiting assignment'):'Runway 24'}</dd></div></dl>${controls}`;
}
function render(){if(!sim)return;const p=sim.planes.find(p=>p.id===selected);$('clock').textContent=formatTime(sim.time);$('movements').innerHTML=`${sim.completed}<span>/ 10</span>`;$('score').textContent=sim.score;$('incidents').textContent=sim.incidents;$('progress').value=sim.time;const remaining=Math.max(0,1200-Math.floor(sim.time));$('remaining').textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')} remaining`;
  const runway=sim.planes.find(p=>p.id===sim.runwayOwner);$('runway-status').textContent=runway?runway.call+' · occupied':'Available';$('runway-badge').classList.toggle('occupied',!!runway);
  const detail=flightDetail(p);if(detail!==lastDetail){$('flight-detail').innerHTML=detail;lastDetail=detail;$('flight-detail').querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>issue(b.dataset.action));if($('preview-route'))$('preview-route').onclick=preview;if($('stand-select'))$('stand-select').onchange=e=>{destination=e.target.value;if(planning)preview();};if($('clear-waypoints'))$('clear-waypoints').onclick=()=>{waypoints=[];preview();};refreshIcons();}
  const planes=sim.planes.filter(p=>p.state!=='done');$('traffic-count').textContent=String(planes.length).padStart(2,'0');$('pending').textContent=`${planes.filter(p=>['gate','ready','inbound','holding','linedup','approach'].includes(p.state)).length} awaiting clearance`;
  const strips=planes.filter(p=>filter==='all'||p.direction===filter).map(p=>`<button class="strip ${p.direction} ${p.id===selected?'selected':''}" data-flight="${p.id}" aria-label="Select ${p.call}"><div class="strip-top"><span class="strip-call">${p.call}</span>${icon(p.direction==='arrival'?'plane-landing':'plane-takeoff')}</div><div class="strip-meta">${p.type} · ${p.direction==='arrival'?'ARR':'DEP'} · ${p.stand?'STAND '+p.stand:'RWY 24'}</div><div class="strip-status"><span>${p.blocked?'Traffic hold':p.held?'Holding position':statusNames[p.state]}</span>${['gate','ready','approach','inbound','holding'].includes(p.state)?'<strong>REQ</strong>':''}</div></button>`).join('')||'<div class="empty">No flights in this queue.</div>';
  if(strips!==lastStrips){$('strips').innerHTML=strips;lastStrips=strips;$('strips').querySelectorAll('[data-flight]').forEach(b=>b.onclick=()=>select(+b.dataset.flight));refreshIcons();}
  const logs=sim.logs.slice(0,12).map(l=>`<div class="log-entry ${l.type}"><time>${formatTime(l.time).slice(3,8)}</time><span>${l.text}</span></div>`).join('');if(logs!==lastLogs){$('radio-log').innerHTML=logs;lastLogs=logs;}
  $('route-banner').hidden=!planning;$('route-banner').textContent=`${waypoints.length?waypoints.length+' via points · ':''}Taxi to ${p?.direction==='arrival'?'stand '+destination:'D1 / runway 24'}`;
}
function restart(){sim.reset();pause(false);select(1);map.fit();lastLogs='';render();}
$('pause').onclick=()=>pause(!paused);document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{speed=+b.dataset.speed;document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render();});
$('zoom-in').onclick=()=>map.zoom(1.3);$('zoom-out').onclick=()=>map.zoom(1/1.3);$('fit').onclick=()=>map.fit();$('labels').onclick=()=>{map.labels=!map.labels;$('labels').classList.toggle('active',map.labels);$('labels').setAttribute('aria-pressed',String(map.labels));};
$('airport-button').onclick=()=>showDialog('airport-dialog');$('select-edinburgh').onclick=()=>$('airport-dialog').close();$('restart').onclick=()=>showDialog('restart-dialog');$('cancel-restart').onclick=()=>$('restart-dialog').close();$('confirm-restart').onclick=()=>{$('restart-dialog').close();restart();};$('play-again').onclick=()=>{$('results-dialog').close();restart();};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['SELECT','BUTTON','INPUT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();pause(!paused);}});
async function start(){try{sim=new GroundSim(airportData);map=new AirportMap($('map'),sim,select,id=>{const p=sim.planes.find(p=>p.id===selected);if(available(p)){if(!planning)preview();if(waypoints.at(-1)!==id)waypoints.push(id);preview();}else toast('Select a flight awaiting taxi, or hold a taxiing flight to revise its route.');});$('map-loading').hidden=true;render();
  const dataDownload=$('airport-dialog').querySelector('a');dataDownload.href=URL.createObjectURL(new Blob([JSON.stringify(airportData)],{type:'application/json'}));dataDownload.download='egph.json';
  // Expose the same commands for browser agents and reproducible simulation checks.
  window.groundControl={sim,map,select,issue,preview,setPaused:pause,getState:()=>({time:sim.time,score:sim.score,completed:sim.completed,runway:sim.runwayOwner,flights:sim.planes.map(({id,call,state,x,y,stand})=>({id,call,state,x,y,stand}))})};
  const context=document.modelContext;if(context?.registerTool){const controller=new AbortController();window.addEventListener('pagehide',()=>controller.abort(),{once:true});for(const tool of [{name:'read_ground_control',description:'Read the airport simulation and flight states.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.groundControl.getState()},{name:'issue_ground_clearance',description:'Issue a clearance to an aircraft using the same rules as the control desk.',inputSchema:{type:'object',properties:{flightId:{type:'integer'},action:{type:'string',enum:['pushback','hold','taxi','lineup','takeoff','land','goaround']},stand:{type:'string'}},required:['flightId','action'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Number.isInteger(input.flightId)||typeof input.action!=='string')throw new Error('Invalid clearance');const result=sim.command(input.flightId,input.action,{stand:input.stand});render();return result;}}]){try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}}}
  let prev=performance.now(),ui=0;function frame(now){let dt=Math.min((now-prev)/1000,.1);prev=now;if(!paused&&!sim.finished){let remaining=dt*speed;while(remaining>0){const step=Math.min(.1,remaining);sim.tick(step);remaining-=step;}}
    map.draw();if(now-ui>200){render();ui=now;}if(sim.finished&&!$('results-dialog').open){$('results').innerHTML=`<p>${sim.completed>=10?'Movement target reached.':'Movement target: '+sim.completed+' / 10'}</p><div>Movements completed <strong>${sim.completed}</strong></div><div>Final score <strong>${sim.score}</strong></div><div>Traffic conflicts / missed arrivals <strong>${sim.incidents}</strong></div>`;showDialog('results-dialog');}requestAnimationFrame(frame);}requestAnimationFrame(frame);
  }catch(error){$('map-loading').textContent=error.message;console.error(error);}}
refreshIcons();start();
